// Code generated by entc, DO NOT EDIT.

package task

import (
	"time"
)

const (
	// Label holds the string label denoting the task type in the database.
	Label = "task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTaskName holds the string denoting the taskname field in the database.
	FieldTaskName = "task_name"
	// FieldTaskLabel holds the string denoting the tasklabel field in the database.
	FieldTaskLabel = "task_label"
	// FieldTaskDate holds the string denoting the taskdate field in the database.
	FieldTaskDate = "task_date"
	// FieldRecurrentTask holds the string denoting the recurrenttask field in the database.
	FieldRecurrentTask = "recurrent_task"
	// FieldTaskTimeInvested holds the string denoting the tasktimeinvested field in the database.
	FieldTaskTimeInvested = "task_time_invested"
	// FieldPeriodicity holds the string denoting the periodicity field in the database.
	FieldPeriodicity = "periodicity"

	// Table holds the table name of the task in the database.
	Table = "tasks"
)

// Columns holds all SQL columns for task fields.
var Columns = []string{
	FieldID,
	FieldTaskName,
	FieldTaskLabel,
	FieldTaskDate,
	FieldRecurrentTask,
	FieldTaskTimeInvested,
	FieldPeriodicity,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TaskNameValidator is a validator for the "TaskName" field. It is called by the builders before save.
	TaskNameValidator func(string) error
	// DefaultTaskLabel holds the default value on creation for the TaskLabel field.
	DefaultTaskLabel string
	// DefaultTaskDate holds the default value on creation for the TaskDate field.
	DefaultTaskDate func() time.Time
	// DefaultRecurrentTask holds the default value on creation for the RecurrentTask field.
	DefaultRecurrentTask bool
)
