// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"
	"todogolist/ent/schema"
	"todogolist/ent/task"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescTaskName is the schema descriptor for TaskName field.
	taskDescTaskName := taskFields[0].Descriptor()
	// task.TaskNameValidator is a validator for the "TaskName" field. It is called by the builders before save.
	task.TaskNameValidator = taskDescTaskName.Validators[0].(func(string) error)
	// taskDescTaskLabel is the schema descriptor for TaskLabel field.
	taskDescTaskLabel := taskFields[1].Descriptor()
	// task.DefaultTaskLabel holds the default value on creation for the TaskLabel field.
	task.DefaultTaskLabel = taskDescTaskLabel.Default.(string)
	// taskDescTaskDate is the schema descriptor for TaskDate field.
	taskDescTaskDate := taskFields[2].Descriptor()
	// task.DefaultTaskDate holds the default value on creation for the TaskDate field.
	task.DefaultTaskDate = taskDescTaskDate.Default.(func() time.Time)
	// taskDescRecurrentTask is the schema descriptor for RecurrentTask field.
	taskDescRecurrentTask := taskFields[3].Descriptor()
	// task.DefaultRecurrentTask holds the default value on creation for the RecurrentTask field.
	task.DefaultRecurrentTask = taskDescRecurrentTask.Default.(bool)
}
